import { archetype } from "./types";
import type { ArchetypeOption } from "./types";

export const ANIMAL_ARCHETYPES: ArchetypeOption[] = [
  archetype({
    name: {"en":"White Wolf","zh":"白狼"},
    tagline: {"en":"Alert and loyal","zh":"警惕而忠诚"},
    keywords: ["cautious","loyal","protect","guard","pack","fierce","lone","trust","警惕","忠诚","保护","守护","狼","孤独","信任"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Canis_lupus_hudsonicus.jpg/400px-Canis_lupus_hudsonicus.jpg",
    shortPoem: {"zh":"警惕而忠诚。\n\n不会轻易靠近任何人，\n却愿意为了重要的人走进暴风雪。","en":"Alert and loyal.\n\nThey will not approach anyone easily,\nyet will walk into blizzards for those who matter."},
    deepAnalysis: {"zh":"白狼在象征体系里代表孤高的忠诚与族群之间的羁绊。","en":"The white wolf represents solitary nobility and fierce pack loyalty."},
    resonanceStory: {"zh":"他们像一匹走在雪线边缘的白狼——独自巡逻，却在听见同伴呼唤时，毫不犹豫地回头。","en":"They are a white wolf on the snow line — patrolling alone, yet turning without hesitation when a companion calls."},
    growthInsight: {"zh":"成长是允许自己从「孤狼」变成「选择孤独或同行」。","en":"Growth is moving from lone wolf to one who chooses solitude or company."},
  }),
  archetype({
    name: {"en":"Arctic Fox","zh":"北极狐"},
    tagline: {"en":"Learning to change color and survive the snow","zh":"在风雪中学会变色与生存"},
    keywords: ["adapt","cautious","clever","survive","cold","watch","change","适应","谨慎","聪明","生存","寒冷","观察","变化","灵活"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Arctic_fox_%28Vulpes_lagopus%29.jpg/400px-Arctic_fox_%28Vulpes_lagopus%29.jpg",
    shortPoem: {"zh":"在风雪中学会变色与生存。\n\n你的角色善于观察环境，\n在必要时调整自己。","en":"Learning to change and survive the snow.\n\nYour character reads the world carefully,\nadapting when they must."},
    deepAnalysis: {"zh":"北极狐随季节变换毛色，象征高度适应力与敏锐的危机感知。","en":"The arctic fox shifts with the seasons — a symbol of adaptability and sharp survival instinct."},
    resonanceStory: {"zh":"他们像雪地里一闪而过的影子——轻巧、警觉、几乎不留下痕迹。","en":"They are a shadow crossing snow — light, alert, leaving almost no trace."},
    growthInsight: {"zh":"成长是在适应世界的同时，不再丢失那个真实的自己。","en":"Growth is adapting without losing the true self."},
  }),
  archetype({
    name: {"en":"Raven","zh":"乌鸦"},
    tagline: {"en":"A wise walker between worlds","zh":"在边界行走的智慧者"},
    keywords: ["clever","smart","mysterious","observe","know","magic","death","secret","聪明","智慧","神秘","观察","知晓","秘密","死亡","预兆"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Corvus_corax.jpg/400px-Corvus_corax.jpg",
    shortPoem: {"zh":"在边界行走的智慧者。\n\n你的角色看得比别人更深，\n却也因此常常显得疏离。","en":"A wise walker between worlds.\n\nYour character sees deeper than most,\nand is often mistaken for distant because of it."},
    deepAnalysis: {"zh":"乌鸦在诸多文化里是通灵者与知识的携带者。","en":"Across cultures, the raven carries knowledge and omens."},
    resonanceStory: {"zh":"他们站在故事与故事之间的阴影里，像乌鸦落在枝头——不喧哗，却一眼看穿局势的走向。","en":"They stand in the shadow between stories, like a raven on a branch — quiet, yet seeing where events will fall."},
    growthInsight: {"zh":"成长是学会把洞察变成连接，而不只是旁观。","en":"Growth is turning insight into connection, not only observation."},
  }),
  archetype({
    name: {"en":"Stag","zh":"雄鹿"},
    tagline: {"en":"Silent leader and embodiment of honor","zh":"沉默的领袖与荣誉的化身"},
    keywords: ["noble","leader","proud","honor","duty","guardian","strong","高贵","领袖","骄傲","荣誉","责任","守护","强大","威严"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Cervus_elaphus_stag.jpg/400px-Cervus_elaphus_stag.jpg",
    shortPoem: {"zh":"沉默的领袖与荣誉的化身。\n\n你的角色习惯承担责任，\n把别人的安全放在自己之前。","en":"Silent leader, embodiment of honor.\n\nYour character carries responsibility naturally,\nplacing others' safety before their own."},
    deepAnalysis: {"zh":"雄鹿象征高贵的领导力与无声的权威。","en":"The stag symbolizes noble leadership and quiet authority."},
    resonanceStory: {"zh":"他们像森林深处那头静立的鹿——不主动攻击，却用存在本身稳住整个族群。","en":"They are the stag standing deep in the forest — not aggressive, yet stabilizing the herd by presence alone."},
    growthInsight: {"zh":"成长是明白：领袖也需要被照顾。","en":"Growth is understanding that leaders need care too."},
  }),
  archetype({
    name: {"en":"Black Cat","zh":"黑猫"},
    tagline: {"en":"An independent soul often misunderstood","zh":"被误解的独立灵魂"},
    keywords: ["independent","alone","misunderstood","intuition","secret","free","独立","孤独","误解","直觉","秘密","自由","神秘","猫"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Black_cat.jpg/400px-Black_cat.jpg",
    shortPoem: {"zh":"被误解的独立灵魂。\n\n你的角色习惯独自行走，\n不是不需要陪伴，而是太熟悉被误读的感觉。","en":"An independent soul, often misunderstood.\n\nYour character walks alone —\nnot because they need no company,\nbut because they know misreading too well."},
    deepAnalysis: {"zh":"黑猫象征独立、直觉与被污名化的优雅。","en":"The black cat symbolizes independence, intuition, and grace under stigma."},
    resonanceStory: {"zh":"他们像夜色里悄然走过的猫——不解释，不讨好，只在想停留的地方停留。","en":"They are a cat moving through night — explaining nothing, pleasing no one, staying only where they wish."},
    growthInsight: {"zh":"成长是找到不必解释也能被看见的关系。","en":"Growth is finding relationships where they are seen without explanation."},
  }),
  archetype({
    name: {"en":"Owl","zh":"猫头鹰"},
    tagline: {"en":"Gathering wisdom in silence","zh":"在沉默中积累智慧"},
    keywords: ["wise","watch","quiet","knowledge","observe","teacher","night","智慧","观察","安静","知识","洞察","老师","夜","沉默"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Bubo_bubo_1.jpg/400px-Bubo_bubo_1.jpg",
    shortPoem: {"zh":"在沉默中积累智慧。\n\n你的角色更擅长倾听与观察，\n而不是急于表达。","en":"Gathering wisdom in silence.\n\nYour character listens and watches\nmore readily than they speak."},
    deepAnalysis: {"zh":"猫头鹰象征通过观察获得的智慧。","en":"The owl symbolizes wisdom earned through watching."},
    resonanceStory: {"zh":"他们像站在枝头的猫头鹰——在所有人都睡去的时候，替世界守着那些未被说出的真相。","en":"They are an owl on the branch — while the world sleeps, keeping watch over truths not yet spoken."},
    growthInsight: {"zh":"成长是把自己看见的东西，适时地说出来。","en":"Growth is speaking what they see, when the moment is right."},
  }),
  archetype({
    name: {"en":"Red Fox","zh":"赤狐"},
    tagline: {"en":"Clever warmth beneath wild caution","zh":"机敏谨慎下的温度"},
    keywords: ["clever","charm","cautious","playful","wit","adapt","sly","聪明","魅力","谨慎","俏皮","机智","适应","赤狐"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Red_fox_%28Vulpes_vulpes%29.jpg/400px-Red_fox_%28Vulpes_vulpes%29.jpg",
    shortPoem: {"zh":"机敏谨慎下的温度。\n\n你的角色懂得进退，\n用轻巧的方式保护自己与所在乎的人。","en":"Clever warmth beneath wild caution.\n\nYour character knows when to advance or retreat,\nprotecting themselves and others with lightness."},
    deepAnalysis: {"zh":"赤狐象征机智、魅力与在危险中保持灵活的判断。","en":"The red fox symbolizes wit, charm, and flexible judgment amid danger."},
    resonanceStory: {"zh":"他们像林缘闪过的赤狐——看似玩笑，实则每一步都经过计算。","en":"They are red fox at the forest edge — seeming playful, yet every step calculated."},
    growthInsight: {"zh":"成长是把聪明用于建立信任，而不只是躲避伤害。","en":"Growth is using cleverness to build trust, not only avoid harm."},
  }),
  archetype({
    name: {"en":"Red-Crowned Crane","zh":"丹顶鹤"},
    tagline: {"en":"Grace that carries longevity and vow","zh":"承载长寿与誓约的优雅"},
    keywords: ["grace","loyal","noble","pair","ritual","elegant","devotion","优雅","忠诚","高贵","伴侣","仪式","典雅","誓约","鹤"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Grus_japonensis.jpg/400px-Grus_japonensis.jpg",
    shortPoem: {"zh":"承载长寿与誓约的优雅。\n\n你的角色对承诺极为看重，\n举止间有一种不慌不忙的尊严。","en":"Grace that carries longevity and vow.\n\nYour character values promises deeply,\nmoving with unhurried dignity."},
    deepAnalysis: {"zh":"丹顶鹤在东亚文化中象征忠贞、长寿与仪式感的秩序。","en":"The red-crowned crane in East Asian culture symbolizes fidelity, longevity, and ritual order."},
    resonanceStory: {"zh":"他们像清晨湿地里的鹤——一步一行，都像在履行某种看不见的约定。","en":"They are crane in morning wetland — each step as if fulfilling an unseen vow."},
    growthInsight: {"zh":"成长是在坚守誓约的同时，也允许关系有呼吸的缝隙。","en":"Growth is holding vows while allowing relationships room to breathe."},
  }),
  archetype({
    name: {"en":"Koi","zh":"锦鲤"},
    tagline: {"en":"Swimming upstream against the current","zh":"逆流而上的坚持"},
    keywords: ["persist","luck","transform","endure","water","hope","courage","坚持","转运","蜕变","忍耐","水","希望","勇气","锦鲤"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Koi_fish.jpg/400px-Koi_fish.jpg",
    shortPoem: {"zh":"逆流而上的坚持。\n\n你的角色在阻力中仍向前，\n把每一次挣扎都当成靠近光的方式。","en":"Swimming upstream against the current.\n\nYour character moves forward against resistance,\ntreating each struggle as a way toward light."},
    deepAnalysis: {"zh":"锦鲤象征逆流而上、转运与在困境中坚持的生命力。","en":"Koi symbolizes swimming upstream, transformation, and persistence in adversity."},
    resonanceStory: {"zh":"他们像池中游动的锦鲤——看似从容，其实一直在对抗水底的方向。","en":"They are koi in a pond — seemingly calm, yet always resisting the pull beneath."},
    growthInsight: {"zh":"成长是辨认哪些逆流值得，哪些只是习惯硬撑。","en":"Growth is knowing which currents are worth fighting, which are mere habit."},
  }),
  archetype({
    name: {"en":"Tiger","zh":"虎"},
    tagline: {"en":"Power held with instinctive pride","zh":"本能骄傲中蕴藏的力量"},
    keywords: ["fierce","proud","power","protect","wild","courage","dominant","凶猛","骄傲","力量","保护","野性","勇气","威严","虎"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Panthera_tigris_tigris.jpg/400px-Panthera_tigris_tigris.jpg",
    shortPoem: {"zh":"本能骄傲中蕴藏的力量。\n\n你的角色有不容忽视的锋芒，\n习惯用行动而不是解释来证明自己。","en":"Power held with instinctive pride.\n\nYour character carries unmistakable edge,\nproving themselves through action, not explanation."},
    deepAnalysis: {"zh":"虎象征力量、威严与保护领地与族群的本能。","en":"Tiger symbolizes power, authority, and instinct to protect territory and kin."},
    resonanceStory: {"zh":"他们像山林里沉默巡行的虎——不常咆哮，却让整个空间改变气压。","en":"They are tiger pacing silent mountains — rarely roaring, yet shifting the air of any room."},
    growthInsight: {"zh":"成长是学会在有力量的同时，也温柔地收起爪。","en":"Growth is learning to soften claws while still holding power."},
  }),
  archetype({
    name: {"en":"Swan","zh":"天鹅"},
    tagline: {"en":"Elegant surface over deep devotion","zh":"优雅水面下的深情"},
    keywords: ["elegant","loyal","devotion","pair","grace","proud","beauty","优雅","忠诚","深情","伴侣","高贵","骄傲","美丽","天鹅"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Mute_swan.jpg/400px-Mute_swan.jpg",
    shortPoem: {"zh":"优雅水面下的深情。\n\n你的角色把浓烈情绪藏在从容举止里，\n一旦认定，便极为专一。","en":"Elegant surface over deep devotion.\n\nYour character hides intensity behind poise —\nonce committed, remarkably devoted."},
    deepAnalysis: {"zh":"天鹅象征优雅、专一与水面下不停划动的坚持。","en":"Swan symbolizes elegance, fidelity, and relentless paddling beneath calm water."},
    resonanceStory: {"zh":"他们像湖上的天鹅——远看宁静，近看才知道一直在用力保持方向。","en":"They are swan on a lake — calm from afar, yet paddling hard to hold course."},
    growthInsight: {"zh":"成长是让人看见水下的努力，而不只是水面的完美。","en":"Growth is letting others see effort beneath perfection."},
  }),
  archetype({
    name: {"en":"Horse","zh":"马"},
    tagline: {"en":"Running toward freedom and duty alike","zh":"奔向自由也奔向责任"},
    keywords: ["free","run","loyal","duty","journey","spirit","wild","自由","奔跑","忠诚","责任","旅程","精神","野性","马"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Horse_in_Mongolia.jpg/400px-Horse_in_Mongolia.jpg",
    shortPoem: {"zh":"奔向自由也奔向责任。\n\n你的角色渴望辽阔，\n却也会在需要时为人驻足。","en":"Running toward freedom and duty alike.\n\nYour character longs for open distance,\nyet will halt for those who need them."},
    deepAnalysis: {"zh":"马象征自由、忠诚与长途跋涉中的意志。","en":"Horse symbolizes freedom, loyalty, and will across long journeys."},
    resonanceStory: {"zh":"他们像原野上回头的马——鬃毛带风，眼神却已在辨认下一道命令或下一次告别。","en":"They are horse turning on open plain — mane in wind, eyes already reading next command or farewell."},
    growthInsight: {"zh":"成长是在奔跑与停留之间找到自己的节奏。","en":"Growth is finding rhythm between running and staying."},
  }),
  archetype({
    name: {"en":"Brown Bear","zh":"棕熊"},
    tagline: {"en":"Fierce guardian with a soft den","zh":"凶猛守护与柔软巢穴"},
    keywords: ["protect","strong","gentle","family","hibernate","guardian","fierce","保护","强大","温柔","家人","冬眠","守护","凶猛","熊"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Brown_bear_%28Ursus_arctos%29.jpg/400px-Brown_bear_%28Ursus_arctos%29.jpg",
    shortPoem: {"zh":"凶猛守护与柔软巢穴。\n\n你的角色对外强硬，\n却把最深的柔软留给极少数人。","en":"Fierce guardian with a soft den.\n\nYour character is hard outwardly,\nyet saves deepest softness for very few."},
    deepAnalysis: {"zh":"棕熊象征强悍的守护本能与在巢穴里的温柔。","en":"Brown bear symbolizes fierce guardianship and tenderness within the den."},
    resonanceStory: {"zh":"他们像入冬前的熊——世界看见爪牙，只有巢穴知道温度。","en":"They are bear before winter — world sees claws, only the den knows warmth."},
    growthInsight: {"zh":"成长是扩大「巢穴」的边界，而不只是扩大防御。","en":"Growth is widening the den, not only the defense."},
  }),
  archetype({
    name: {"en":"Monarch Butterfly","zh":"帝王蝶"},
    tagline: {"en":"Fragile wings on impossible journeys","zh":"脆弱翅膀走完漫长旅程"},
    keywords: ["transform","fragile","journey","hope","change","light","delicate","蜕变","脆弱","旅程","希望","改变","轻盈","蝴蝶"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Monarch_Butterfly.jpg/400px-Monarch_Butterfly.jpg",
    shortPoem: {"zh":"脆弱翅膀走完漫长旅程。\n\n你的角色经历过蜕变，\n因此比外表看起来更耐风雨。","en":"Fragile wings on impossible journeys.\n\nYour character has transformed,\nand is more weathered than they appear."},
    deepAnalysis: {"zh":"帝王蝶象征蜕变、脆弱与跨越不可能的迁徙。","en":"Monarch butterfly symbolizes transformation, fragility, and impossible migration."},
    resonanceStory: {"zh":"他们像逆风飞行的蝶——轻得让人担心，却有自己的方向感。","en":"They are butterfly flying against wind — light enough to worry others, yet directionally sure."},
    growthInsight: {"zh":"成长是承认脆弱，同时信任自己已经飞过很多段路。","en":"Growth is acknowledging fragility while trusting miles already flown."},
  }),
  archetype({
    name: {"en":"Dolphin","zh":"海豚"},
    tagline: {"en":"Intelligence woven with playful empathy","zh":"聪慧与玩心交织的共情"},
    keywords: ["clever","social","playful","empathy","communicate","joy","heal","聪明","社交","玩心","共情","沟通","快乐","治愈","海豚"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Dolphin.jpg/400px-Dolphin.jpg",
    shortPoem: {"zh":"聪慧与玩心交织的共情。\n\n你的角色善于读懂气氛，\n用幽默和温度化解紧绷。","en":"Intelligence woven with playful empathy.\n\nYour character reads the room,\neasing tension through humor and warmth."},
    deepAnalysis: {"zh":"海豚象征高社会性、沟通力与在群体中疗愈他人的能力。","en":"Dolphin symbolizes social intelligence, communication, and healing within groups."},
    resonanceStory: {"zh":"他们像浪尖跃出的海豚——把沉重托举成一瞬间的明亮。","en":"They are dolphin leaping from waves — lifting heaviness into brief brightness."},
    growthInsight: {"zh":"成长是在照顾群体时，也认真倾听自己的回声。","en":"Growth is listening to one's own echo while caring for the pod."},
  }),
  archetype({
    name: {"en":"Peregrine Falcon","zh":"猎隼"},
    tagline: {"en":"Focus sharpened at impossible speed","zh":"极致专注与惊人速度"},
    keywords: ["focus","speed","precision","hunt","sharp","goal","decisive","专注","速度","精准","狩猎","锐利","目标","果断","隼"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Falco_peregrinus.jpg/400px-Falco_peregrinus.jpg",
    shortPoem: {"zh":"极致专注与惊人速度。\n\n你的角色一旦锁定目标，\n便很少被情绪拖慢脚步。","en":"Focus sharpened at impossible speed.\n\nOnce your character locks onto a goal,\nemotion rarely slows their stride."},
    deepAnalysis: {"zh":"猎隼象征极致专注、决断与高空俯瞰的清醒。","en":"Peregrine falcon symbolizes extreme focus, decisiveness, and clarity from height."},
    resonanceStory: {"zh":"他们像云层之上的隼——世界缩小成一点，其他都变成风。","en":"They are falcon above clouds — world reduced to a point, everything else becoming wind."},
    growthInsight: {"zh":"成长是学会在俯冲之外，也有停驻的枝头。","en":"Growth is learning to perch, not only dive."},
  }),
  archetype({
    name: {"en":"Sea Turtle","zh":"海龟"},
    tagline: {"en":"Ancient patience crossing vast water","zh":"穿越汪洋的古老耐心"},
    keywords: ["patient","ancient","endure","journey","home","calm","persist","耐心","古老","忍耐","旅程","归家","平静","坚持","海龟"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Green_Sea_Turtle.jpg/400px-Green_Sea_Turtle.jpg",
    shortPoem: {"zh":"穿越汪洋的古老耐心。\n\n你的角色节奏很慢，\n却极少真正放弃。","en":"Ancient patience crossing vast water.\n\nYour character moves slowly,\nyet rarely truly gives up."},
    deepAnalysis: {"zh":"海龟象征耐心、归巢本能与跨越大距离的坚持。","en":"Sea turtle symbolizes patience, homing instinct, and persistence across vast distance."},
    resonanceStory: {"zh":"他们像夜海里缓慢划水的龟——外人只见平静，看不见四肢从未停下。","en":"They are turtle paddling in night sea — calm on surface, limbs never still below."},
    growthInsight: {"zh":"成长是接受自己的慢，同时相信慢也能抵达。","en":"Growth is accepting one's slowness while trusting it still arrives."},
  }),
  archetype({
    name: {"en":"Serpent","zh":"蛇"},
    tagline: {"en":"Renewal through shedding old skin","zh":"蜕皮中完成自我更新"},
    keywords: ["renew","mysterious","transform","heal","danger","wise","hidden","更新","神秘","蜕变","治愈","危险","智慧","隐藏","蛇"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Python_molurus_molurus.jpg/400px-Python_molurus_molurus.jpg",
    shortPoem: {"zh":"蜕皮中完成自我更新。\n\n你的角色习惯周期性自我推翻，\n在危险与重生之间行走。","en":"Renewal through shedding old skin.\n\nYour character periodically remakes themselves,\nwalking between danger and rebirth."},
    deepAnalysis: {"zh":"蛇在许多文化中象征蜕变、治愈与危险的智慧。","en":"Serpent across cultures symbolizes transformation, healing, and dangerous wisdom."},
    resonanceStory: {"zh":"他们像石缝里蜕皮的蛇——旧身份留下，新的那一层已经更亮。","en":"They are serpent shedding in stone crevice — old skin left behind, new layer already brighter."},
    growthInsight: {"zh":"成长是把蜕皮变成有意识的选择，而不是被动的创伤反应。","en":"Growth is making shedding a conscious choice, not only trauma's reflex."},
  }),
  archetype({
    name: {"en":"Rabbit","zh":"兔"},
    tagline: {"en":"Soft vigilance in a dangerous world","zh":"柔软警觉里的生存"},
    keywords: ["gentle","alert","timid","quick","soft","survive","nervous","温柔","警觉","胆怯","敏捷","柔软","生存","紧张","兔"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Oryctolagus_cuniculus.jpg/400px-Oryctolagus_cuniculus.jpg",
    shortPoem: {"zh":"柔软警觉里的生存。\n\n你的角色外表温顺，\n内心却对危险保持高度敏感。","en":"Soft vigilance in a dangerous world.\n\nYour character seems gentle outwardly,\nyet stays highly alert to danger within."},
    deepAnalysis: {"zh":"兔象征柔软、敏捷与在威胁中快速反应的本能。","en":"Rabbit symbolizes softness, agility, and instinct to react swiftly to threat."},
    resonanceStory: {"zh":"他们像草丛里竖耳的兔——一动就知风向，一停就把世界藏进绒毛里。","en":"They are rabbit with ears raised in grass — sensing wind at a twitch, hiding the world in fur when still."},
    growthInsight: {"zh":"成长是在保持警觉的同时，也允许自己真正放松片刻。","en":"Growth is allowing real rest while keeping healthy alertness."},
  }),
  archetype({
    name: {"en":"Grey Wolf","zh":"灰狼"},
    tagline: {"en":"Pack loyalty forged in the wild","zh":"荒野里锻造的族群忠诚"},
    keywords: ["loyal","pack","hunt","cooperate","wild","bond","leader","忠诚","族群","狩猎","合作","野性","羁绊","领袖","狼"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Canis_lupus.jpg/400px-Canis_lupus.jpg",
    shortPoem: {"zh":"荒野里锻造的族群忠诚。\n\n你的角色重视归属，\n愿意为集体承担风险。","en":"Pack loyalty forged in the wild.\n\nYour character values belonging,\nwilling to risk for the collective."},
    deepAnalysis: {"zh":"灰狼象征合作、族群羁绊与在野性中形成的秩序。","en":"Grey wolf symbolizes cooperation, pack bonds, and order formed in wildness."},
    resonanceStory: {"zh":"他们像月夜荒原上的狼群一员——嚎叫不是为了恐吓，而是为了确认彼此还在。","en":"They are one wolf on moonlit plain — howling not to frighten, but to confirm others remain."},
    growthInsight: {"zh":"成长是在忠于族群的同时，也保留独立的判断。","en":"Growth is staying loyal to the pack while keeping independent judgment."},
  }),
  archetype({
    name: {"en":"Elephant","zh":"象"},
    tagline: {"en":"Memory that carries the herd forward","zh":"承载族群前行的记忆"},
    keywords: ["memory","gentle","strong","family","mourn","wise","protect","记忆","温柔","强大","家族","哀悼","智慧","保护","象"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/African_bush_elephant.jpg/400px-African_bush_elephant.jpg",
    shortPoem: {"zh":"承载族群前行的记忆。\n\n你的角色记得太多过往，\n因此比别人更懂如何照顾弱者。","en":"Memory that carries the herd forward.\n\nYour character remembers much,\nand therefore knows better how to care for the vulnerable."},
    deepAnalysis: {"zh":"象象征家族记忆、温柔的力量与哀悼中的智慧。","en":"Elephant symbolizes family memory, gentle strength, and wisdom within mourning."},
    resonanceStory: {"zh":"他们像象群里的成象——用身体挡住风，也用记忆挡住遗忘。","en":"They are adult elephant in the herd — blocking wind with body, blocking forgetting with memory."},
    growthInsight: {"zh":"成长是学会放下一些记忆的重量，而不忘记如何温柔。","en":"Growth is setting down some memory's weight without losing tenderness."},
  }),
  archetype({
    name: {"en":"Hummingbird","zh":"蜂鸟"},
    tagline: {"en":"Small body, impossible endurance","zh":"微小身躯里的惊人耐力"},
    keywords: ["energetic","small","hope","joy","quick","delicate","vibrant","活力","微小","希望","快乐","敏捷","纤细","热烈","蜂鸟"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Archilochus_colubris.jpg/400px-Archilochus_colubris.jpg",
    shortPoem: {"zh":"微小身躯里的惊人耐力。\n\n你的角色看似轻盈，\n却能在高压下持续振动翅膀。","en":"Small body, impossible endurance.\n\nYour character seems light,\nyet can keep beating wings under pressure."},
    deepAnalysis: {"zh":"蜂鸟象征微小身躯中的巨大能量与对甜美的执着追寻。","en":"Hummingbird symbolizes vast energy in a small body and relentless pursuit of sweetness."},
    resonanceStory: {"zh":"他们像花间的蜂鸟——停驻极短，动作极快，却把春天钉在原地。","en":"They are hummingbird among flowers — brief stillness, rapid motion, pinning spring in place."},
    growthInsight: {"zh":"成长是学会在振翅之余，也找到可以真正停下的花。","en":"Growth is finding a flower where wings can truly rest."},
  }),
  archetype({
    name: {"en":"Emperor Penguin","zh":"企鹅"},
    tagline: {"en":"Enduring cold for those who come after","zh":"为后来者忍受严寒"},
    keywords: ["endure","cold","parent","duty","community","persist","sacrifice","忍耐","寒冷","父母","责任","群体","坚持","牺牲","企鹅"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Emperor_penguin.jpg/400px-Emperor_penguin.jpg",
    shortPoem: {"zh":"为后来者忍受严寒。\n\n你的角色愿意在艰难环境里坚守，\n把牺牲当成对他人的承诺。","en":"Enduring cold for those who come after.\n\nYour character holds ground in harsh conditions,\ntreating sacrifice as promise to others."},
    deepAnalysis: {"zh":"帝企鹅象征在极端环境中的集体忍耐与为后代坚守的责任。","en":"Emperor penguin symbolizes collective endurance in extremes and duty to those who follow."},
    resonanceStory: {"zh":"他们像风雪里相拥的企鹅——体温不是为自己，而是为下一轮生命。","en":"They are penguins huddled in blizzard — warmth not for self, but for life to come."},
    growthInsight: {"zh":"成长是在承担责任的同时，也允许自己离开寒风片刻。","en":"Growth is carrying duty while permitting brief leave from the cold."},
  }),
  archetype({
    name: {"en":"Snow Leopard","zh":"雪豹"},
    tagline: {"en":"Solitary grace on unreachable heights","zh":"高处的孤独优雅"},
    keywords: ["solitary","rare","grace","mountain","stealth","proud","cold","孤独","稀有","优雅","高山","隐匿","骄傲","寒冷","雪豹"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Snow_leopard.jpg/400px-Snow_leopard.jpg",
    shortPoem: {"zh":"高处的孤独优雅。\n\n你的角色习惯独处高处，\n以稀有为代价换取自由。","en":"Solitary grace on unreachable heights.\n\nYour character keeps to high solitude,\ntrading rarity for freedom."},
    deepAnalysis: {"zh":"雪豹象征稀有、孤高与在绝境环境中的隐匿力量。","en":"Snow leopard symbolizes rarity, solitary nobility, and hidden power in extreme terrain."},
    resonanceStory: {"zh":"他们像雪线之上的豹——足迹稀少，却让整个山脉知道有人守望。","en":"They are leopard above the snowline — few tracks, yet the whole range knows someone watches."},
    growthInsight: {"zh":"成长是走下高处时不失去优雅，也不把孤独当成唯一的安全。","en":"Growth is descending without losing grace, nor making solitude the only safety."},
  }),
];
