import { archetype } from "./types";
import type { ArchetypeOption } from "./types";

export const PLANT_ARCHETYPES: ArchetypeOption[] = [
  archetype({
    name: {"en":"White Camellia","zh":"白山茶"},
    tagline: {"en":"Quietly blooming through the cold season","zh":"安静地盛开在寒冷季节"},
    keywords: ["loyal","quiet","guard","protect","dignity","gentle","reserved","忠诚","安静","守护","保护","尊严","温柔","内敛","冷淡"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Camellia_japonica_%27Alba_Plena%27.jpg/400px-Camellia_japonica_%27Alba_Plena%27.jpg",
    shortPoem: {"zh":"安静地盛开在寒冷季节。\n\n即使经历过失去，\n依然保留温柔与善意。\n\n你的角色并不擅长表达感情，\n却总是在最重要的时候陪伴别人。","en":"Quietly blooming through the cold season.\n\nEven after loss,\ntenderness and kindness remain.\n\nYour character rarely speaks their heart,\nyet always appears when it matters most."},
    deepAnalysis: {"zh":"白山茶在东亚文化里象征含蓄的爱与不屈的尊严。它不张扬，却在最艰难的季节里依然选择开放——这与你角色「外冷内热」的情感结构高度吻合。","en":"In East Asian symbolism, white camellia stands for restrained affection and unyielding dignity. It does not perform its beauty — it persists through harsh seasons."},
    resonanceStory: {"zh":"如果把你角色的人生写成一首诗，它会是冬日里的一株白山茶——经历风雪，却未忘记如何温柔。","en":"If your character's life were a poem, it would be white camellia in winter — weathered by frost, yet never forgetting how to be gentle."},
    growthInsight: {"zh":"角色的成长方向，是学会在守护别人的同时，也允许自己被守护。","en":"Their growth lies in learning to be guarded and held at once — to protect others while allowing themselves to be cared for."},
  }),
  archetype({
    name: {"en":"Night-Blooming Cereus","zh":"夜昙"},
    tagline: {"en":"Blooming fully only in nights no one watches","zh":"只在无人注视的夜里，短暂而完整地绽放"},
    keywords: ["mysterious","hidden","secret","night","solitude","introvert","rare","神秘","隐藏","秘密","孤独","内向","稀有","沉默"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Epiphyllum_oxypetalum_%28Queen_of_the_Night%29.jpg/400px-Epiphyllum_oxypetalum_%28Queen_of_the_Night%29.jpg",
    shortPoem: {"zh":"只在无人注视的夜里，\n短暂而完整地绽放。\n\n你的角色习惯把真实藏在深处，\n不是不愿被看见，\n而是害怕被误读。","en":"Blooming fully only in unwatched nights.\n\nYour character keeps truth folded inward —\nnot because they refuse to be seen,\nbut because they fear being misread."},
    deepAnalysis: {"zh":"夜昙的美是瞬息的、私密的。它象征那些只在安全空间里才完整呈现的自我。","en":"The night-blooming cereus is fleeting and intimate — beauty revealed only when the world is not looking."},
    resonanceStory: {"zh":"他们像一朵只在深夜开放的花——白天是寻常的样子，夜晚才是完整的自己。","en":"They are a flower that opens only after dark — ordinary by day, complete by night."},
    growthInsight: {"zh":"成长意味着找到值得绽放的对象——不是向所有人敞开，而是不再把全部的自己永远藏在夜里。","en":"Growth means finding someone worth blooming for — not performing for everyone, but no longer keeping their whole self locked in eternal night."},
  }),
  archetype({
    name: {"en":"Wild Ivy","zh":"野藤"},
    tagline: {"en":"Growing through cracks, clinging through storms","zh":"在裂缝里生长，在风雨里攀附"},
    keywords: ["survivor","stubborn","persist","war","trauma","hold","tenacious","生存","固执","坚持","创伤","顽强","韧性","不放弃"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Hedera_helix_002.jpg/400px-Hedera_helix_002.jpg",
    shortPoem: {"zh":"在裂缝里生长，在风雨里攀附。\n\n你的角色经历过太多，\n却始终没有放弃。","en":"Growing through cracks, holding on through storms.\n\nYour character has endured much,\nyet never stopped moving forward."},
    deepAnalysis: {"zh":"野藤象征在逆境中依然寻找依附与方向的生存本能。","en":"Wild ivy symbolizes survival instinct — finding hold and direction even in ruin."},
    resonanceStory: {"zh":"他们像藤蔓一样，把根扎在最不容易的地方，却把枝叶伸向光。","en":"Like ivy, they root in the hardest places yet reach toward light."},
    growthInsight: {"zh":"真正的成长，是学会在攀附之外，也能独立站立。","en":"True growth is learning to stand without always clinging."},
  }),
  archetype({
    name: {"en":"Cherry Blossom","zh":"樱花"},
    tagline: {"en":"Brief beauty and the tenderness of letting go","zh":"短暂的美，与接受消逝的温柔"},
    keywords: ["beauty","loss","memory","sorrow","accept","friend","childhood","美丽","失去","记忆","悲伤","接受","朋友","童年","怀念"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Cherry_Blossoms_at_the_Imperial_Palace%2C_Tokyo.jpg/400px-Cherry_Blossoms_at_the_Imperial_Palace%2C_Tokyo.jpg",
    shortPoem: {"zh":"短暂的美，与接受消逝的温柔。\n\n你的角色懂得失去的重量，\n因此更珍惜当下的每一刻。","en":"Brief beauty and the grace of impermanence.\n\nYour character knows the weight of loss,\nand cherishes each present moment."},
    deepAnalysis: {"zh":"樱花在日本美学里代表物哀——美正因为会消逝而更加珍贵。","en":"Cherry blossom embodies mono no aware — beauty intensified by impermanence."},
    resonanceStory: {"zh":"每当风吹过，他们仿佛都能看见过往的花瓣。","en":"When the wind rises, they almost see past petals falling again."},
    growthInsight: {"zh":"成长不是忘记，而是带着记忆继续生活。","en":"Growth is not forgetting, but living forward with memory."},
  }),
  archetype({
    name: {"en":"Thorned Rose","zh":"带刺玫瑰"},
    tagline: {"en":"Thorns guarding a soft heart","zh":"用刺保护柔软的心"},
    keywords: ["passion","anger","fierce","boundaries","defensive","protect","sharp","热情","愤怒","激烈","边界","防御","保护","尖锐","刺"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Rosa_rubiginosa_1.jpg/400px-Rosa_rubiginosa_1.jpg",
    shortPoem: {"zh":"用刺保护柔软的心。\n\n你的角色看起来不好接近，\n但那只是因为他们太清楚真心一旦被伤害，很难再次完整。","en":"Thorns guarding a soft heart.\n\nYour character seems hard to approach —\nbecause they know how difficult it is to become whole again after being hurt."},
    deepAnalysis: {"zh":"玫瑰的刺不是攻击，而是边界。你的角色用尖锐的外表保护内在的热烈与真诚。","en":"The rose's thorns are boundaries, not weapons. Your character shields fierce sincerity behind sharp edges."},
    resonanceStory: {"zh":"他们像一朵开在荒原上的玫瑰——美丽、危险、令人想要靠近又不敢轻易触碰。","en":"They are a rose on barren ground — beautiful, dangerous, drawing people near while warning them away."},
    growthInsight: {"zh":"成长是学会区分：哪些刺是必要的防御，哪些刺只是习惯。","en":"Growth means learning which thorns are necessary defense and which are habit."},
  }),
  archetype({
    name: {"en":"Willow","zh":"垂柳"},
    tagline: {"en":"Bending in the wind without breaking","zh":"在风中弯曲，却不折断"},
    keywords: ["grief","sad","flexible","adapt","empathy","mourn","gentle","soft","悲伤","柔韧","适应","共情","哀悼","温柔","柔软","敏感"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Weeping_willow_in_Budapest.jpg/400px-Weeping_willow_in_Budapest.jpg",
    shortPoem: {"zh":"在风中弯曲，却不折断。\n\n你的角色承载过很多情绪——\n自己的，也包括别人的。","en":"Bending in the wind without breaking.\n\nYour character has carried much emotion —\ntheir own, and others' too."},
    deepAnalysis: {"zh":"垂柳象征柔韧的哀伤与深层的共情。","en":"Willow symbolizes flexible grief and deep empathy."},
    resonanceStory: {"zh":"他们总在水边、在风里、在别人的眼泪旁边。","en":"They are found by water, in wind, beside others' tears."},
    growthInsight: {"zh":"成长是学会在共情的同时保留自我。","en":"Growth is empathizing without losing the self."},
  }),
  archetype({
    name: {"en":"Bamboo","zh":"翠竹"},
    tagline: {"en":"Standing tall yet bending with grace","zh":"挺拔而柔韧，随风而不折"},
    keywords: ["integrity","flexible","upright","patience","growth","resilient","honor","正直","柔韧","挺拔","耐心","成长","韧性","气节","竹"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Bamboo.jpg/400px-Bamboo.jpg",
    shortPoem: {"zh":"挺拔而柔韧，随风而不折。\n\n你的角色有清晰的原则，\n却懂得在必要时弯腰。","en":"Standing tall yet bending with grace.\n\nYour character holds clear principles,\nyet knows when to yield."},
    deepAnalysis: {"zh":"竹在中国文化里象征君子之德：外直内空，虚心有节。","en":"Bamboo in Chinese culture embodies the noble person — upright, hollow-hearted, jointed with integrity."},
    resonanceStory: {"zh":"他们像竹林里的一竿翠竹——风来时全体摇曳，根却始终相连。","en":"They are one stalk in a bamboo grove — swaying together in wind, yet rooted in shared ground."},
    growthInsight: {"zh":"成长是在坚守本心的同时，学会与风共处而非对抗一切。","en":"Growth is holding one's core while learning to move with the wind, not against everything."},
  }),
  archetype({
    name: {"en":"Lotus","zh":"莲花"},
    tagline: {"en":"Rising pure from murky depths","zh":"出淤泥而不染"},
    keywords: ["pure","calm","spiritual","detached","rebirth","grace","noble","纯净","宁静","超脱","重生","优雅","高贵","莲"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Nelumbo_nucifera_%28fruit%29.jpg/400px-Nelumbo_nucifera_%28fruit%29.jpg",
    shortPoem: {"zh":"出淤泥而不染。\n\n你的角色在复杂环境里，\n仍努力守住内心的澄澈。","en":"Rising pure from murky depths.\n\nYour character strives to keep inner clarity\namid complicated surroundings."},
    deepAnalysis: {"zh":"莲花象征在困境中保持精神洁净与超然。","en":"Lotus symbolizes spiritual purity and detachment within difficulty."},
    resonanceStory: {"zh":"他们像夏日池塘里悄然升起的莲——根在泥里，花在光中。","en":"They are lotus rising from a summer pond — roots in mud, bloom in light."},
    growthInsight: {"zh":"成长不是逃离淤泥，而是在其中依然选择开放。","en":"Growth is not escaping the mud, but choosing to bloom within it."},
  }),
  archetype({
    name: {"en":"Plum Blossom","zh":"梅花"},
    tagline: {"en":"Blooming alone against winter frost","zh":"凌寒独自开"},
    keywords: ["proud","lonely","endure","courage","winter","fragrant","solitary","傲骨","孤独","忍耐","勇气","寒冬","清香","梅"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Prunus_mume.jpg/400px-Prunus_mume.jpg",
    shortPoem: {"zh":"凌寒独自开。\n\n你的角色习惯在无人喝彩时坚持，\n把力量藏在看似孤单的选择里。","en":"Blooming alone against winter frost.\n\nYour character persists without applause,\nhiding strength inside solitary choices."},
    deepAnalysis: {"zh":"梅花象征逆境中的孤高与先发之美。","en":"Plum blossom symbolizes proud solitude and beauty that arrives before comfort."},
    resonanceStory: {"zh":"他们像雪地里第一枝梅——不等人来，便已盛开。","en":"They are the first plum branch in snow — blooming before anyone arrives."},
    growthInsight: {"zh":"成长是学会把孤勇转化为被理解的坚持，而非永远的隔绝。","en":"Growth is turning solitary courage into perseverance that can be understood."},
  }),
  archetype({
    name: {"en":"Chrysanthemum","zh":"菊花"},
    tagline: {"en":"Late-blooming dignity in autumn air","zh":"秋霜中迟开的高洁"},
    keywords: ["autumn","dignity","endure","literary","reclusive","loyal","longevity","秋","高洁","忍耐","文人","隐逸","忠诚","长寿","菊"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Chrysanthemum_morifolium.jpg/400px-Chrysanthemum_morifolium.jpg",
    shortPoem: {"zh":"秋霜中迟开的高洁。\n\n你的角色不抢春日的热闹，\n却在别人退场时依然站定。","en":"Late-blooming dignity in autumn air.\n\nYour character avoids spring's noise,\nyet remains when others have left."},
    deepAnalysis: {"zh":"菊花在东方文化中象征晚节、隐逸与经得起时间考验的品格。","en":"Chrysanthemum in East Asian culture stands for late integrity, reclusion, and character that endures time."},
    resonanceStory: {"zh":"他们像秋后篱边的菊——不喧哗，却把清苦化成一种气味。","en":"They are chrysanthemum by the autumn fence — quiet, turning bitterness into fragrance."},
    growthInsight: {"zh":"成长是接受自己的节奏不必最早，却必须最真。","en":"Growth is accepting that one's timing need not be earliest, only most true."},
  }),
  archetype({
    name: {"en":"Orchid","zh":"兰花"},
    tagline: {"en":"Elegance found in quiet corners","zh":"幽谷自芳"},
    keywords: ["refined","elegant","quiet","noble","solitary","sensitive","artistic","清雅","优雅","安静","高贵","独处","敏感","艺术","兰"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Cymbidium_goeringii.jpg/400px-Cymbidium_goeringii.jpg",
    shortPoem: {"zh":"幽谷自芳。\n\n你的角色有一种不迎合的优雅，\n在角落里也能自成风景。","en":"Elegance found in quiet corners.\n\nYour character carries unperformative grace,\nbecoming scenery even in obscurity."},
    deepAnalysis: {"zh":"兰象征清逸、自守与审美上的克制。","en":"Orchid symbolizes refined restraint and grace that needs no audience."},
    resonanceStory: {"zh":"他们像深谷里的兰——不攀高枝，却把香气留给靠近的人。","en":"They are orchid in a deep valley — not climbing high branches, yet leaving fragrance for those who approach."},
    growthInsight: {"zh":"成长是走出幽谷时，仍保留那份不讨好的清雅。","en":"Growth is leaving the valley while keeping grace that never flatters."},
  }),
  archetype({
    name: {"en":"Ginkgo","zh":"银杏"},
    tagline: {"en":"Ancient witness to changing seasons","zh":"穿越季节的古意"},
    keywords: ["memory","ancient","witness","change","hope","longevity","golden","记忆","古老","见证","变迁","希望","长寿","金黄","银杏"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Ginkgo_biloba_tree.jpg/400px-Ginkgo_biloba_tree.jpg",
    shortPoem: {"zh":"穿越季节的古意。\n\n你的角色像时间的见证者，\n记得太多，也因此比别人更慢一步。","en":"Ancient witness to changing seasons.\n\nYour character remembers deeply,\nand therefore moves a step slower than others."},
    deepAnalysis: {"zh":"银杏象征长寿、记忆与秋日里迟来的金色希望。","en":"Ginkgo symbolizes longevity, memory, and late golden hope in autumn."},
    resonanceStory: {"zh":"他们站在故事里，像一棵老银杏——叶落时整条路都变成过去。","en":"They stand in the story like an old ginkgo — when leaves fall, the whole road becomes the past."},
    growthInsight: {"zh":"成长是学会携带记忆前行，而不是被记忆留在原地。","en":"Growth is carrying memory forward, not being held in place by it."},
  }),
  archetype({
    name: {"en":"Pine","zh":"青松"},
    tagline: {"en":"Evergreen through snow and storm","zh":"风雪中的常青"},
    keywords: ["steadfast","endure","loyal","guardian","winter","pine","resolute","坚定","忍耐","忠诚","守护","寒冬","松","刚毅"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Pinus_sylvestris_tree.jpg/400px-Pinus_sylvestris_tree.jpg",
    shortPoem: {"zh":"风雪中的常青。\n\n你的角色在压力下保持镇定，\n像松一样沉默而可靠。","en":"Evergreen through snow and storm.\n\nYour character stays steady under pressure —\nsilent and dependable as pine."},
    deepAnalysis: {"zh":"青松象征岁寒不凋的坚毅与守望。","en":"Pine symbolizes endurance that does not fade in winter and quiet watchfulness."},
    resonanceStory: {"zh":"他们像山巅上的松——不追繁华，却替风雪守住轮廓。","en":"They are pine on a mountain ridge — not chasing splendor, yet holding shape against snow."},
    growthInsight: {"zh":"成长是明白常青不等于无感，而是允许自己在寒夜里依然呼吸。","en":"Growth is knowing evergreen does not mean numb — breathing still through cold nights."},
  }),
  archetype({
    name: {"en":"Lavender","zh":"薰衣草"},
    tagline: {"en":"Fragrance that soothes restless minds","zh":"安抚不安的淡紫芬芳"},
    keywords: ["calm","heal","soothe","dream","gentle","anxiety","peace","平静","治愈","安抚","梦境","温柔","焦虑","安宁","薰衣草"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Lavender_flowers_2.jpg/400px-Lavender_flowers_2.jpg",
    shortPoem: {"zh":"安抚不安的淡紫芬芳。\n\n你的角色有一种让人放松的气场，\n擅长把尖锐情绪化成柔软的晚风。","en":"Fragrance that soothes restless minds.\n\nYour character eases the room they enter,\nturning sharp moods into soft evening air."},
    deepAnalysis: {"zh":"薰衣草象征疗愈、安宁与对敏感情绪的抚慰。","en":"Lavender symbolizes healing, calm, and comfort for sensitive emotion."},
    resonanceStory: {"zh":"他们像薰衣草田边的风——不解决一切，却让人终于敢深呼吸。","en":"They are wind beside a lavender field — not solving everything, but letting others breathe."},
    growthInsight: {"zh":"成长是在照顾别人情绪的同时，也为自己留一片安静的田。","en":"Growth is tending others' feelings while keeping a quiet field for oneself."},
  }),
  archetype({
    name: {"en":"Sunflower","zh":"向日葵"},
    tagline: {"en":"Turning toward light without apology","zh":"毫不掩饰地朝向光"},
    keywords: ["optimistic","bright","loyal","open","warm","hope","sincere","乐观","明亮","忠诚","开朗","温暖","希望","真诚","向日葵"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Helianthus_annuus_002.jpg/400px-Helianthus_annuus_002.jpg",
    shortPoem: {"zh":"毫不掩饰地朝向光。\n\n你的角色把热忱写在脸上，\n哪怕世界阴沉，也仍相信明天。","en":"Turning toward light without apology.\n\nYour character wears warmth openly,\nbelieving in tomorrow even when skies are grey."},
    deepAnalysis: {"zh":"向日葵象征坦荡的忠诚与向光而生的生命力。","en":"Sunflower symbolizes unhidden loyalty and life that orients toward light."},
    resonanceStory: {"zh":"他们像盛夏田野里的向日葵——热烈、直接，让人一眼就知道方向。","en":"They are sunflower in midsummer fields — fervent, direct, direction visible at a glance."},
    growthInsight: {"zh":"成长是学会向光不等于忽视阴影，而是在阴影里仍记得如何转头。","en":"Growth is knowing turning toward light does not deny shadow — only remembering how to turn."},
  }),
  archetype({
    name: {"en":"Desert Cactus","zh":"仙人掌"},
    tagline: {"en":"Storing tenderness behind tough skin","zh":"把柔软储存在坚硬里"},
    keywords: ["independent","defensive","survive","dry","reserved","protect","thorn","独立","防御","生存","干旱","内敛","保护","刺","仙人掌"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Cactus_in_Tel_Aviv.jpg/400px-Cactus_in_Tel_Aviv.jpg",
    shortPoem: {"zh":"把柔软储存在坚硬里。\n\n你的角色在贫瘠环境里学会自保，\n刺不是冷漠，而是活下来的语法。","en":"Storing tenderness behind tough skin.\n\nYour character learned self-protection in scarcity —\nthorns are not coldness, but grammar of survival."},
    deepAnalysis: {"zh":"仙人掌象征在资源匮乏中保存水分与边界的生存智慧。","en":"Cactus symbolizes survival wisdom — storing water and boundaries in scarcity."},
    resonanceStory: {"zh":"他们像沙漠里静默的仙人掌——远看坚硬，近看却藏着缓慢生长的绿。","en":"They are cactus in silent desert — hard from afar, yet green growing slowly within."},
    growthInsight: {"zh":"成长是在仍需要刺的时候保留它，在安全里允许自己开花。","en":"Growth is keeping thorns when needed, yet allowing bloom where it is safe."},
  }),
  archetype({
    name: {"en":"Dandelion","zh":"蒲公英"},
    tagline: {"en":"Carrying wishes on the wind","zh":"把愿望交给风"},
    keywords: ["free","wander","hope","resilient","light","childlike","drift","自由","漂泊","希望","顽强","轻盈","童真","随风","蒲公英"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Taraxacum_officinale_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-20.jpg/400px-Taraxacum_officinale_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-20.jpg",
    shortPoem: {"zh":"把愿望交给风。\n\n你的角色身上有种轻盈的倔强，\n即使被吹散，也会在新的地方生根。","en":"Carrying wishes on the wind.\n\nYour character holds a light stubbornness —\nscattered, yet rooting again wherever they land."},
    deepAnalysis: {"zh":"蒲公英象征漂泊中的希望与看似脆弱实则顽强的生命。","en":"Dandelion symbolizes hope in wandering and life that seems fragile yet persists."},
    resonanceStory: {"zh":"他们像被风吹起的蒲公英——旅程不确定，却从不真正消失。","en":"They are dandelion lifted by wind — journey uncertain, yet never truly gone."},
    growthInsight: {"zh":"成长是学会主动选择去向，而不只是被风带走。","en":"Growth is choosing direction, not only being carried by wind."},
  }),
  archetype({
    name: {"en":"Moss","zh":"苔藓"},
    tagline: {"en":"Quiet green on forgotten stones","zh":"被遗忘石面上的安静绿意"},
    keywords: ["humble","quiet","patient","cover","soft","overlooked","endure","谦卑","安静","耐心","覆盖","柔软","被忽视","忍耐","苔藓"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Moss_closeup.jpg/400px-Moss_closeup.jpg",
    shortPoem: {"zh":"被遗忘石面上的安静绿意。\n\n你的角色不争夺舞台中心，\n却在角落里维持着不易察觉的温度。","en":"Quiet green on forgotten stones.\n\nYour character avoids the spotlight,\nyet keeps subtle warmth in corners."},
    deepAnalysis: {"zh":"苔藓象征谦卑、耐心与被忽视却持续存在的生命力。","en":"Moss symbolizes humility, patience, and life that persists unnoticed."},
    resonanceStory: {"zh":"他们像石阶缝隙里的苔——无人称赞，却把潮湿的日子变成绿色。","en":"They are moss in stone cracks — unpraised, yet turning damp days green."},
    growthInsight: {"zh":"成长是承认微小也是一种力量，并允许自己被看见。","en":"Growth is accepting smallness as power, and allowing oneself to be seen."},
  }),
  archetype({
    name: {"en":"Magnolia","zh":"玉兰"},
    tagline: {"en":"Opening before leaves dare appear","zh":"叶未生花先放"},
    keywords: ["noble","pure","early","courage","grace","dignity","bloom","高贵","纯净","抢先","勇气","优雅","尊严","玉兰"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Magnolia_soulangeana.jpg/400px-Magnolia_soulangeana.jpg",
    shortPoem: {"zh":"叶未生花先放。\n\n你的角色敢于率先表达，\n在环境尚未准备好时便已行动。","en":"Opening before leaves dare appear.\n\nYour character acts before the world is ready,\nexpressing before others find words."},
    deepAnalysis: {"zh":"玉兰象征抢先绽放的勇气与不带叶饰的纯粹。","en":"Magnolia symbolizes courage to bloom first and purity without ornament."},
    resonanceStory: {"zh":"他们像早春枝头的玉兰——花先一步，把整个季节叫醒。","en":"They are magnolia on early branches — flower first, waking the season."},
    growthInsight: {"zh":"成长是在抢先一步时，也学会等待别人跟上。","en":"Growth is leading boldly while learning to wait for others to catch up."},
  }),
  archetype({
    name: {"en":"Peony","zh":"牡丹"},
    tagline: {"en":"Fullness that commands the garden","zh":"盛放时令满园失色"},
    keywords: ["glory","passion","wealth","proud","generous","dramatic","bloom","荣耀","热情","富贵","骄傲","慷慨","张扬","牡丹"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Paeonia_suffruticosa.jpg/400px-Paeonia_suffruticosa.jpg",
    shortPoem: {"zh":"盛放时令满园失色。\n\n你的角色有不容忽视的存在感，\n慷慨、热烈，也带着天生的骄傲。","en":"Fullness that commands the garden.\n\nYour character commands attention —\ngenerous, fervent, proudly present."},
    deepAnalysis: {"zh":"牡丹象征富贵、圆满与毫不掩饰的生命张力。","en":"Peony symbolizes abundance, fullness, and unhidden vital force."},
    resonanceStory: {"zh":"他们像暮春园中的牡丹——一开便占满所有目光，也愿把美分享给靠近的人。","en":"They are peony in late spring garden — blooming to fill every gaze, sharing beauty with those near."},
    growthInsight: {"zh":"成长是在盛放时仍保留给予的空间，而不只是被仰望。","en":"Growth is keeping room to give while in full bloom, not only being admired."},
  }),
  archetype({
    name: {"en":"Wisteria","zh":"紫藤"},
    tagline: {"en":"Cascading longing in purple rain","zh":"垂落的紫色思念"},
    keywords: ["longing","romantic","dream","attach","cascade","nostalgia","yearn","思念","浪漫","梦境","依附","垂落","怀旧","渴望","紫藤"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Wisteria_sinensis.jpg/400px-Wisteria_sinensis.jpg",
    shortPoem: {"zh":"垂落的紫色思念。\n\n你的角色对羁绊有绵长的眷恋，\n把未说完的话都挂在时间里。","en":"Cascading longing in purple rain.\n\nYour character holds long attachment,\nhanging unfinished words across time."},
    deepAnalysis: {"zh":"紫藤象征绵延的思念与浪漫化的依附。","en":"Wisteria symbolizes extended longing and romanticized attachment."},
    resonanceStory: {"zh":"他们像老宅廊下的紫藤——年年垂落，年年记得同一个人、同一个夏天。","en":"They are wisteria under an old corridor — falling yearly, remembering the same person, the same summer."},
    growthInsight: {"zh":"成长是学会把思念化成前进，而不只是垂落。","en":"Growth is turning longing into movement, not only cascade."},
  }),
  archetype({
    name: {"en":"Oak","zh":"橡树"},
    tagline: {"en":"Deep roots holding generations","zh":"深根承载世代"},
    keywords: ["stable","protect","heritage","strong","shelter","endure","guardian","稳固","保护","传承","强大","庇护","忍耐","守护","橡树"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Quercus_robur.jpg/400px-Quercus_robur.jpg",
    shortPoem: {"zh":"深根承载世代。\n\n你的角色是他人可以依靠的结构，\n沉默地承担，很少为自己喊累。","en":"Deep roots holding generations.\n\nYour character is structure others lean on —\nshouldering quietly, rarely complaining."},
    deepAnalysis: {"zh":"橡树象征稳固、庇护与跨代际的守护。","en":"Oak symbolizes stability, shelter, and guardianship across generations."},
    resonanceStory: {"zh":"他们像原野上的老橡——树冠宽广，根在地下比任何人都更深。","en":"They are old oak on open land — wide canopy, roots deeper underground than anyone knows."},
    growthInsight: {"zh":"成长是允许自己也需要荫蔽，而不只是为别人遮风挡雨。","en":"Growth is allowing oneself shade too, not only giving shelter."},
  }),
  archetype({
    name: {"en":"Fern","zh":"蕨类"},
    tagline: {"en":"Unfurling slowly in shaded light","zh":"在阴影里缓缓舒展"},
    keywords: ["quiet","ancient","adapt","shade","delicate","grow","hidden","安静","古老","适应","阴影","纤细","生长","隐藏","蕨"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Fern_frond.jpg/400px-Fern_frond.jpg",
    shortPoem: {"zh":"在阴影里缓缓舒展。\n\n你的角色在不被注视处慢慢成长，\n把脆弱化成一种持续的展开。","en":"Unfurling slowly in shaded light.\n\nYour character grows where few look,\nturning fragility into steady unfolding."},
    deepAnalysis: {"zh":"蕨类象征古老、适应阴影与缓慢而确定的生长。","en":"Fern symbolizes ancient life, adaptation to shade, and slow certain growth."},
    resonanceStory: {"zh":"他们像林间蕨叶——一圈圈展开，从不要求掌声。","en":"They are forest fern — unfurling ring by ring, never asking for applause."},
    growthInsight: {"zh":"成长是走出阴影时，仍保留那份不急躁的展开。","en":"Growth is leaving shade while keeping unhurried unfolding."},
  }),
  archetype({
    name: {"en":"Reed","zh":"芦苇"},
    tagline: {"en":"Swaying with tides yet rooted still","zh":"随潮摇摆却扎根不移"},
    keywords: ["adapt","flexible","border","lonely","wind","water","resilient","适应","柔韧","边界","孤独","风","水","韧性","芦苇"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Phragmites_australis.jpg/400px-Phragmites_australis.jpg",
    shortPoem: {"zh":"随潮摇摆却扎根不移。\n\n你的角色处在流动的边界上，\n懂得妥协，却从不真正漂走。","en":"Swaying with tides yet rooted still.\n\nYour character lives on moving borders —\ncompromising, yet never truly drifting away."},
    deepAnalysis: {"zh":"芦苇象征水岸边界上的柔韧与孤独守望。","en":"Reed symbolizes flexibility on water's edge and solitary watch."},
    resonanceStory: {"zh":"他们像秋风吹过的芦苇荡——声响很大，根却一直在同一片水里。","en":"They are reed bed in autumn wind — loud in sound, yet rooted in the same water."},
    growthInsight: {"zh":"成长是在摇摆中辨认自己的岸，而不只是随风倾倒。","en":"Growth is recognizing one's shore while swaying, not only bending with every wind."},
  }),
];
